apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: jenkins
spec:
  serviceAccountName: jenkins-sa
  nodeSelector:
    kubernetes.io/arch: amd64
  containers:
    - name: kaniko
      image: gaussye/kaniko-full:latest
      command:
        - sleep
      args:
        - 99d
  restartPolicy: Never
