apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nerdctl
  name: nerdctl
spec:
  containers:
    - name: nerdctl
      image: gaussye/nerdctl:20230921-01-arm64
      tty: true
      securityContext:
        privileged: true
        runAsUser: 0
  restartPolicy: Always
