apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nerdctl
  name: nerdctl
spec:
  containers:
    - name: nerdctl
      image: gaussye/nerdctlrootless:latest
      tty: true
      resources:
        limits:
          cpu: 3000m
          memory: 5Gi
        requests:
          cpu: 3000m
          memory: 5Gi
      securityContext:
        privileged: true
        runAsUser: 0
  restartPolicy: Always
