apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nerdctl
  name: nerdctl
spec:
  nodeSelector:
    kubernetes.io/arch: amd64
  containers:
    - name: nerdctl
      image: gaussye/nerdctl-full:latest
      tty: true
      securityContext:
        privileged: true
        runAsUser: 0
  restartPolicy: Always
